config/routes.rb
TvTracker::Application.routes.draw do

  resources :channels
  resources :tv_shows
  
  root :to => 'tv_shows#index'

end

app/models/channel.rb
# == Schema Information
#
# Table name: channels
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  channel_no :integer
#  created_at :datetime
#  updated_at :datetime
#

class Channel < ActiveRecord::Base
  
  has_many :tv_shows, :primary_key => "channel_no"
  
end

app/models/planner.rb
# == Schema Information
#
# Table name: planners
#
#  id         :integer         not null, primary key
#  day        :string(255)
#  start_time :time
#  tv_show_id :integer
#  created_at :datetime
#  updated_at :datetime
#

class Planner < ActiveRecord::Base

	belongs_to :tv_show

	has_one :channel, :through => :tv_show

end

app/models/tv_show.rb
# == Schema Information
#
# Table name: tv_shows
#
#  id           :integer         not null, primary key
#  name         :string(255)
#  season       :integer
#  currently_on :boolean
#  channel_id   :integer
#  last_on      :date
#  us_season    :integer
#  created_at   :datetime
#  updated_at   :datetime
#

class TvShow < ActiveRecord::Base
  
  belongs_to :channel, :primary_key => "channel_no"
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController

  # GET /channels
  # GET /channels.xml
  def index
    @channels = Channel.find(:all, :order => "channel_no")
  end

  # GET /channels/new
  # GET /channels/new.xml
  def new
    @channel = Channel.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @channel }
    end
  end

  # GET /channels/1/edit
  def edit
    @channel = Channel.find(params[:id])
  end

  # POST /channels
  # POST /channels.xml
  def create
    @channel = Channel.new(params[:channel])

    respond_to do |format|
      if @channel.save
        format.html { redirect_to(channels_url, :notice => 'Channel was successfully created.') }
        format.xml  { render :xml => @channel, :status => :created, :location => @channel }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @channels.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /channels/1
  # PUT /channels/1.xml
  def update
    @channel = Channel.find(params[:id])

    respond_to do |format|
      if @channel.update_attributes(params[:channel])
        format.html { redirect_to(channels_url, :notice => 'Channel was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @channel.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.xml
  def destroy
    @channel = Channel.find(params[:id])
    @channel.destroy

    respond_to do |format|
      format.html { redirect_to(channels_url) }
      format.xml  { head :ok }
    end
  end

end

app/controllers/tv_shows_controller.rb
class TvShowsController < ApplicationController
  # GET /tv_shows
  # GET /tv_shows.xml
  def index
    @tv_shows = TvShow.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tv_shows }
    end
  end

  # GET /tv_shows/new
  # GET /tv_shows/new.xml
  def new
    @tv_show = TvShow.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @tv_show }
    end
  end

  # GET /tv_shows/1/edit
  def edit
    @tv_show = TvShow.find(params[:id])
  end

  # POST /tv_shows
  # POST /tv_shows.xml
  def create
    @tv_show = TvShow.new(params[:tv_show])

    respond_to do |format|
      if @tv_show.save
        format.html { redirect_to(tv_shows_url, :notice => 'TV show was successfully created.') }
        format.xml  { render :xml => @tv_show, :status => :created, :location => @tv_show }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tv_show.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tv_shows/1
  # PUT /tv_shows/1.xml
  def update
    @tv_show = TvShow.find(params[:id])

    respond_to do |format|
      if @tv_show.update_attributes(params[:tv_show])
        format.html { redirect_to(tv_shows_url, :notice => 'TV show was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tv_show.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tv_shows/1
  # DELETE /tv_shows/1.xml
  def destroy
    @tv_show = TvShow.find(params[:id])
    @tv_show.destroy

    respond_to do |format|
      format.html { redirect_to(tv_shows_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/channel_helper.rb
module ChannelHelper
  
end

app/helpers/tv_shows_helper.rb
module TvShowsHelper
  
  def channel_list
    @channels = Channel.find(:all, :order => :name)
  end

  def last_on_text(tv_show)
    if tv_show.last_on.nil? 
      "Showing now"
    else  
      tv_show.last_on.strftime("%b %Y")
    end
  end

end

app/views/channels/_form.html.erb
<%= form_for(@channel) do |f| %>
  <% if @channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@channel.errors.count, "error") %> prohibited this Show from being saved:</h2>

      <ul>
      <% @channel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :channel_no %><br />
    <%= f.number_field :channel_no, :in => 101...999,:size => 10 %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/channels/edit.html.erb
<h1>Editing this Channel</h1>

<%= render 'form' %>

<%= link_to 'Show', @channel %> |
<%= link_to 'Back', channels_path %>

app/views/channels/index.html.erb
<h1>Channels</h1>

<table id="newspaper-b" summary="List of all my TV Shows">
	<thead>
	  <tr>
	    <th scope ="col">Channel</th>
	    <th scope ="col">Name</th>
	    <th scope ="col"></th>
	    <th scope ="col"></th>
	  </tr>
	</thead>

<% @channels.each do |channel| %>
  <tr>
    <td id="name"><%= channel.channel_no %></td>
    <td><%= channel.name %></td>
    <td><%= link_to 'Edit', edit_channel_path(channel) %></td>
    <td><%= link_to 'Delete', channel, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= button_to 'New Channel', new_channel_path %><br />
<%= link_to 'Go to Shows', tv_shows_path %>

app/views/channels/new.html.erb
<h1>Add a Channel</h1>

<%= render 'form' %>

<%= link_to 'Show', @channel %> |
<%= link_to 'Back', channels_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>TV Tracker</title>
	  <%= stylesheet_link_tag :all %>
	  <%= javascript_include_tag :defaults %>
	  <%= csrf_meta_tag %>
	</head>
	<body>

		<%= yield %>

		<%= debug(params) if Rails.env.development? %>
	</body>
</html>

app/views/tv_shows/_form.html.erb
<%= form_for(@tv_show) do |f| %>
  <% if @tv_show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tv_show.errors.count, "error") %> prohibited this Show from being saved:</h2>

      <ul>
      <% @tv_show.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :season %><br />
    <%= f.number_field :season, :size => 5 %>
  </div>
  <div class="field">
    <%= f.label :currently_on %>:
    <%= f.check_box :currently_on  %>
  </div>
  <div class="field">
    <%= f.label :channel_id %><br />
		<%= f.collection_select :channel_id, channel_list, :channel_no, :name %>
  </div>
  <div class="field">
    <%= f.label :last_on %><br />
    <%= f.date_select :last_on, :order => [:month, :year] %>
  </div>
  <div class="field">
    US Season<br />
    <%= f.number_field :us_season, :size => 5 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tv_shows/edit.html.erb
<h1>Editing this TV Show</h1>

<%= render 'form' %>

<%= link_to 'Show', @tv_show %> |
<%= link_to 'Back', tv_shows_path %>

app/views/tv_shows/index.html.erb
<h1>TV Shows</h1>

<table id="newspaper-b" summary="List of all my TV Shows">
	<thead>
	  <tr>
	    <th scope ="col">Name</th>
	    <th scope ="col">Channel</th>
	    <th scope ="col">Season</th>
	    <th scope ="col">Currently on</th>
	    <th scope ="col">Last on</th>
	    <th scope ="col">US season</th>
	    <th scope ="col"></th>
	    <th scope ="col"></th>
	  </tr>
	</thead>

<% @tv_shows.each do |tv_show| %>
  <tr>
    <td id="name"><%= tv_show.name %></td>
    <td><%= tv_show.channel.name %></td>
    <td><%= tv_show.season %></td>
    <td>
			<% if tv_show.currently_on.blank? %>
				No
			<% else %>
				Yes
			<% end %>
		</td>
    <td>
			<%= last_on_text tv_show %>

		</td>
    <td><%= tv_show.us_season %></td>
    <td><%= link_to 'Edit', edit_tv_show_path(tv_show) %></td>
    <td><%= link_to 'Delete', tv_show, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= button_to 'New Show',{ :controller => "tv_shows", :action => "new" }, :method => :get %><br />
<%= link_to 'Go to Channels', channels_path %>

app/views/tv_shows/new.html.erb
<h1>New TV Show</h1>

<%= render 'form' %>

<%= link_to 'Back', tv_shows_path %>